spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'aendermich'
  jpa:
    hibernate:
      ddl-auto: update
