server:
  port: 8080
spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'aendermich'
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
